x = mtcars
head(x)
str(x)
mean(x$mpg)
var(x$mpg)
IQR(x$mpg)
median(x$mpg)
sd(x$mpg)
summary(x)
quantiles = quantile(x$mpg)
print(quantiles)
summary(iris$Sepal.Length)
summary(iris$Sepal.Width)
summary(iris$Petal.Length)
summary(iris$Petal.Width)
lapply(x[,1:4],sd)
